"use client";

import { Camera, ChevronDown, GitCompareArrows, Search, X } from "lucide-react";
import { KeyboardEvent, useEffect, useMemo, useRef, useState } from "react";

type Token = { text: string; kind: string };
type Snapshot = { id:string; name:string; code:string; createdAt:string };
function tokenize(code: string): Token[] { const pattern=/(#[^\n]*|"""[\s\S]*?"""|'''[\s\S]*?'''|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\b(?:def|return|if|else|elif|for|while|in|not|and|or|from|import|as|raise|True|False|None|class|with|try|except)\b|\b\d+(?:\.\d+)?\b)/g;const result:Token[]=[];let last=0;for(const match of code.matchAll(pattern)){if(match.index!>last)result.push({text:code.slice(last,match.index),kind:"plain"});const text=match[0];result.push({text,kind:text.startsWith("#")?"comment":/^['\"]/.test(text)?"string":/^\d/.test(text)?"number":"keyword"});last=match.index!+text.length;}if(last<code.length)result.push({text:code.slice(last),kind:"plain"});return result; }
function diffLines(value:string,standard:string){const a=value.split("\n"),b=standard.split("\n");return Array.from({length:Math.max(a.length,b.length)},(_,i)=>a[i]===b[i]?null:{line:i+1,current:a[i]??"",standard:b[i]??""}).filter(Boolean) as {line:number;current:string;standard:string}[];}

export default function CodeEditor({ value,onChange,errorLine,label,lessonId,standardValue,onRun }: { value:string;onChange:(value:string)=>void;errorLine?:number|null;label:string;lessonId:string;standardValue:string;onRun:()=>void }) {
  const [scroll,setScroll]=useState({top:0,left:0});const [searchOpen,setSearchOpen]=useState(false);const [diffOpen,setDiffOpen]=useState(false);const [snapshots,setSnapshots]=useState<Snapshot[]>([]);const [query,setQuery]=useState("");const [replacement,setReplacement]=useState("");const textareaRef=useRef<HTMLTextAreaElement>(null);const tokens=useMemo(()=>tokenize(value),[value]);const lines=value.split("\n").length;const differences=useMemo(()=>diffLines(value,standardValue),[standardValue,value]);const snapshotKey=`quant-code-snapshots-v1-${lessonId}`;
  useEffect(()=>{try{setSnapshots(JSON.parse(localStorage.getItem(snapshotKey)??"[]"))}catch{setSnapshots([])}},[snapshotKey]);
  function replaceSelection(text:string,start:number,end:number,caret=start+text.length){const next=value.slice(0,start)+text+value.slice(end);const textarea=textareaRef.current;if(textarea){textarea.value=next;textarea.selectionStart=textarea.selectionEnd=caret;}onChange(next);queueMicrotask(()=>{if(textareaRef.current){textareaRef.current.selectionStart=textareaRef.current.selectionEnd=caret;textareaRef.current.focus();}})}
  function keyDown(event:KeyboardEvent<HTMLTextAreaElement>){const target=event.currentTarget,start=target.selectionStart,end=target.selectionEnd;if((event.metaKey||event.ctrlKey)&&event.key==="Enter"){event.preventDefault();onRun();return}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="f"){event.preventDefault();setSearchOpen(true);return}if(event.key==="Tab"){event.preventDefault();if(start!==end){const selected=value.slice(start,end);const changed=event.shiftKey?selected.replace(/^ {1,4}/gm,""):selected.replace(/^/gm,"    ");replaceSelection(changed,start,end,start+changed.length);}else replaceSelection("    ",start,end);return}const pairs:Record<string,string>={"(":")","[":"]","{":"}",'"':'"',"'":"'"};if(pairs[event.key]){event.preventDefault();const selected=value.slice(start,end);replaceSelection(event.key+selected+pairs[event.key],start,end,start+1+selected.length);return}if(event.key==="Enter"){const current=value.slice(0,start).split("\n").at(-1)??"";const indent=current.match(/^\s*/)?.[0]??"";const extra=current.trimEnd().endsWith(":")?"    ":"";event.preventDefault();replaceSelection("\n"+indent+extra,start,end);}}
  function saveSnapshot(){const name=window.prompt("快照名称",`版本 ${snapshots.length+1}`)?.trim();if(!name)return;const next=[{id:crypto.randomUUID(),name,code:value,createdAt:new Date().toISOString()},...snapshots].slice(0,20);setSnapshots(next);localStorage.setItem(snapshotKey,JSON.stringify(next));}
  const matches=query?[...value.matchAll(new RegExp(query.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"gi"))].length:0;
  return <div className="code-editor-shell">
    {(searchOpen||diffOpen)&&<div className="editor-panel">{searchOpen&&<div className="editor-search"><Search/><input aria-label="搜索代码" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索"/><input aria-label="替换代码" value={replacement} onChange={e=>setReplacement(e.target.value)} placeholder="替换为"/><span>{matches} 处</span><button onClick={()=>query&&onChange(value.replaceAll(query,replacement))}>全部替换</button><button onClick={()=>setSearchOpen(false)}><X/></button></div>}{diffOpen&&<div className="editor-diff"><div><b>与标准实现对照</b><span>{differences.length} 行不同</span><button onClick={()=>setDiffOpen(false)}><X/></button></div>{differences.slice(0,12).map(item=><p key={item.line}><i>L{item.line}</i><del>{item.standard||"∅"}</del><ins>{item.current||"∅"}</ins></p>)}</div>}</div>}
    <div className="code-gutter" style={{transform:`translateY(${-scroll.top}px)`}}>{Array.from({length:lines},(_,index)=><i className={errorLine===index+1?"error":""} key={index}>{index+1}</i>)}</div>
    <div className="code-editor-layer"><pre aria-hidden style={{transform:`translate(${-scroll.left}px, ${-scroll.top}px)`}}>{tokens.map((token,index)=><span className={`token-${token.kind}`} key={index}>{token.text}</span>)}</pre><textarea ref={textareaRef} aria-label={label} spellCheck={false} value={value} onKeyDown={keyDown} onScroll={event=>setScroll({top:event.currentTarget.scrollTop,left:event.currentTarget.scrollLeft})} onChange={event=>onChange(event.target.value)}/></div>
    <div className="editor-status">{errorLine&&<b>错误定位 · L{errorLine}</b>}<button onClick={()=>setSearchOpen(v=>!v)}><Search/>搜索</button><button onClick={()=>setDiffOpen(v=>!v)}><GitCompareArrows/>差异 {differences.length}</button><button onClick={saveSnapshot}><Camera/>快照</button>{snapshots.length>0&&<label>恢复版本<ChevronDown/><select aria-label="恢复代码快照" value="" onChange={e=>{const found=snapshots.find(item=>item.id===e.target.value);if(found)onChange(found.code)}}><option value="">{snapshots.length} 个快照</option>{snapshots.map(item=><option value={item.id} key={item.id}>{item.name} · {new Date(item.createdAt).toLocaleDateString("zh-CN")}</option>)}</select></label>}<span>⌘↵ 运行</span><span>Python 3</span><span>{lines} 行</span></div>
  </div>;
}
