"use client";

import { CheckCircle2, CloudOff, Download, HardDriveDownload, RefreshCw, Trash2, Wifi } from "lucide-react";
import { useEffect, useState } from "react";

type InstallPrompt = Event & { prompt:()=>Promise<void>; userChoice:Promise<{outcome:"accepted"|"dismissed"}> };
export default function PwaCenter(){const [online,setOnline]=useState(true);const [install,setInstall]=useState<InstallPrompt|null>(null);const [status,setStatus]=useState("等待缓存");const [progress,setProgress]=useState(0);const [installed,setInstalled]=useState(false);const [update,setUpdate]=useState(false);
useEffect(()=>{setOnline(navigator.onLine);setInstalled(matchMedia("(display-mode: standalone)").matches);const connection=()=>setOnline(navigator.onLine);const before=(event:Event)=>{event.preventDefault();setInstall(event as InstallPrompt)};window.addEventListener("online",connection);window.addEventListener("offline",connection);window.addEventListener("beforeinstallprompt",before);if("serviceWorker" in navigator){navigator.serviceWorker.register("/sw.js").then(reg=>{if(reg.waiting)setUpdate(true);reg.addEventListener("updatefound",()=>reg.installing?.addEventListener("statechange",()=>{if(reg.waiting)setUpdate(true)}));});navigator.serviceWorker.addEventListener("message",event=>{if(event.data.type==="CACHE_PROGRESS"){setProgress(Math.round(event.data.done/event.data.total*100));setStatus(`缓存 ${event.data.done}/${event.data.total}`)}if(event.data.type==="CACHE_COMPLETE"){setProgress(100);setStatus(`已缓存 ${event.data.total} 项课程资源`);localStorage.setItem("quant-offline-ready-v1",JSON.stringify({time:new Date().toISOString(),total:event.data.total,version:event.data.version}))}if(event.data.type==="OFFLINE_CLEARED"){setProgress(0);setStatus("离线课程包已清理")}})}return()=>{window.removeEventListener("online",connection);window.removeEventListener("offline",connection);window.removeEventListener("beforeinstallprompt",before)}},[]);
function send(type:string){navigator.serviceWorker.controller?.postMessage({type});if(!navigator.serviceWorker.controller)setStatus("Service Worker 正在接管页面，请刷新后重试")}
return <section className="pwa-center" id="offline"><div className="pwa-copy"><p className="section-kicker">离线与安装</p><h2>把 53 节课程带到没有网络的地方。</h2><p>离线包包含课程页面、完整代码、固定数据和结果快照；浏览器 Python 核心在首次联网运行后由浏览器缓存。</p></div><div className="pwa-status"><span className={online?"online":"offline"}>{online?<Wifi/>:<CloudOff/>}<b>{online?"在线":"离线"}</b><small>{installed?"已作为应用运行":"浏览器模式"}</small></span><span><HardDriveDownload/><b>{progress}%</b><small>{status}</small></span>{update&&<span className="update"><RefreshCw/><b>发现更新</b><small>可立即切换版本</small></span>}</div><div className="pwa-progress"><i><b style={{width:`${progress}%`}}/></i><span>{progress===100?<><CheckCircle2/>离线课程已就绪</>:"下载过程可离开本区，页面保持可用"}</span></div><div className="pwa-actions"><button onClick={()=>send("CACHE_COURSE")} disabled={!online}><Download/>下载离线课程</button>{install&&!installed&&<button onClick={async()=>{await install.prompt();const choice=await install.userChoice;if(choice.outcome==="accepted")setInstalled(true);setInstall(null)}}><HardDriveDownload/>安装到设备</button>}{update&&<button onClick={()=>send("SKIP_WAITING")}><RefreshCw/>应用新版本</button>}<button onClick={()=>send("CLEAR_OFFLINE")}><Trash2/>清理离线包</button></div></section>}
