"use client";

import { CheckCircle2, DatabaseBackup, HardDrive, RotateCcw, ShieldAlert, Upload } from "lucide-react";
import { ChangeEvent, useEffect, useState } from "react";
import { createBackup, restoreBackup, storageHealth, validateBackup } from "@/data/backupStore";

function downloadBackup(){const backup=createBackup();const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`quant-course-backup-${backup.createdAt.slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);}
export default function ReliabilityCenter(){const [health,setHealth]=useState({entries:0,bytes:0,corrupt:0});const [message,setMessage]=useState("");useEffect(()=>setHealth(storageHealth()),[]);async function importFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;try{const backup=validateBackup(JSON.parse(await file.text()));restoreBackup(backup);setMessage(`已恢复 ${Object.keys(backup.entries).length} 条记录，页面即将刷新。`);setTimeout(()=>location.reload(),900);}catch(error){setMessage(error instanceof Error?error.message:"恢复失败");}event.target.value="";}
return <section className="reliability-center" id="reliability"><div><p className="section-kicker">可靠性中心</p><h2>学习成果可备份，也可完整恢复。</h2><p>备份包含课程进度、代码草稿、运行记录、参数实验和六阶段项目；导入前会检查版本与校验码。</p></div><div className="reliability-health"><HardDrive size={18}/><span><b>{health.entries}</b><small>本地记录</small></span><span><b>{(health.bytes/1024).toFixed(1)} KB</b><small>占用空间</small></span><span className={health.corrupt?"bad":"good"}>{health.corrupt?<ShieldAlert/>:<CheckCircle2/>}<b>{health.corrupt||"健康"}</b><small>{health.corrupt?"条损坏记录":"结构检查通过"}</small></span></div><div className="reliability-actions"><button onClick={downloadBackup}><DatabaseBackup size={15}/> 导出完整备份</button><label><Upload size={15}/> 从 JSON 恢复<input type="file" accept="application/json" onChange={importFile}/></label><button onClick={()=>{Object.keys(localStorage).filter(key=>key.startsWith("quant-last-runtime-v1-")).forEach(key=>localStorage.removeItem(key));setMessage("已清理运行状态缓存；学习记录仍然保留。");}}><RotateCcw size={15}/> 重置运行状态</button></div>{message&&<p className="reliability-message">{message}</p>}</section>}
